Use .section .rodata instead of a plain .rodata
At least gcc 12 on Fedora is very unhappy about a plain .rodata and throws
Error: unknown pseudo-op: `.rodata'. So add a .section in front of it to
make it happy.

ok deraadt miod

(cherry picked from commit eda85684cdcfde70d84443a28caf40467d147bfc)