unbreak GENERIC build on amd64; patch by anton@
vmm.c:900:3: error: implicit declaration of function 'x86_send_ipi' is
invalid in C99 [-Werror,-Wimplicit-function-declaration]

(cherry picked from commit ed78bf927f6039213a83328c55f12679b8101f21)